---

- name: configure {{ postgres_config_file }}
  lineinfile:
    dest: "{{ postgres_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {regexp: "^#?wal_level = .*", line: "wal_level = replica" }
    - {regexp: "^#?synchronous_commit = .*", line: "synchronous_commit = local" }
    - {regexp: "^#?archive_mode = .*", line: "archive_mode = on"}
    - {regexp: "^#?archive_command = .*", line: "archive_command = 'cp %p {{ postgres_data_directory }}/archive/%f'" }
    - {regexp: "^#?max_wal_senders = .*", line: "max_wal_senders = 10"}
    - {regexp: "^#?wal_keep_segments = .*", line: "wal_keep_segments = 32" }
    - {regexp: "^#?max_replication_slots = .*", line: "max_replication_slots  = 10" }
  become: True

- name: Create a new directory, change its permission, and change the owner to the postgres user.
  file:
    path: "{{ archive_dir }}"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: '0700'

- name: debug hostvars
  debug:
     msg: "{{ hostvars[item]['ansible_facts']['default_ipv4']['address'] }}"
  with_items: "{{ groups['SLAVE_HOST'] }}"
  when: item in groups[cluster_name]
  
- name:  add all slave IPs to pg_hba.conf
  postgresql_pg_hba:
    dest: "{{ postgres_hba_file }}"
    contype: host
    users: replicator
    source: "{{ hostvars[item]['ansible_facts']['default_ipv4']['address'] }}/32" 
    databases: replication
    method: md5
  with_items: "{{ groups['SLAVE_HOST'] }}"
  when: item in groups[cluster_name]

- name: Create replica  user, set password
  postgresql_user:
    name: replicator
    state: present
    password: "{{ postgres_replica_pass }}"
    role_attr_flags: REPLICATION
    encrypted: yes
  become: true
  become_user: postgres

- name: restart postgres
  service: 
      name: "postgresql-{{ version }}"
      state: restarted

- name: set replication slot for slaves
  become: true
  become_user: postgres
  postgresql_query:
             db: postgres
             query: select * from pg_create_physical_replication_slot(%s)
             positional_args:
                 - "{{ item | lower | replace('-','_') }}"
  with_items: "{{ groups['SLAVE_HOST'] }}"
  when: item in groups[cluster_name]