---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml

# tasks file for postgresql-prevalidation
- name: host checklist post update for  provisioning validation
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_all.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "Pre Validation"
    task_id: "{{ ticket_ref }}"
    task_status: "STARTED"
    task_message: "Prevalidations for Provisioning on {{ ansible_hostname }}"
    standard_task_id: "{{ standard_task_id }}"
  tags:
  - apex_api
#TODO: add  ansible_distribution precheck
- name: generate checklist output
  set_fact:
    checklist:
    # - check_name: Linux distro version
    #   expected_value: "{{ distro_version }}"
    #   actual_value: "{{ ansible_distribution_major_version }}"
    #   status: "{% if ansible_distribution_major_version not in distro_version  -%}FAILED
    #             {%- else -%}PASSED
    #             {%- endif %}"
    - check_name: CPU count
      expected_value: " {{ cpu_count_prereq }}  or more"
      actual_value: "{{ ansible_processor_count }}"
      status: "{% if ansible_processor_count | int < cpu_count_prereq |int -%}FAILED
               {%- else -%}PASSED
               {%- endif %}"
    - check_name: core per cpu count
      expected_value: " {{ core_count_prereq }}  or more"
      actual_value: "{{ ansible_processor_cores }}"
      status: "{% if ansible_processor_cores | int < core_count_prereq |default('1') |int -%}FAILED
               {%- else -%}PASSED
               {%- endif %}"
    - check_name: memory count
      expected_value: "{{ ram_prereq_mb }} or higher"
      actual_value: "{{ ansible_memory_mb.real.total }}"
      status: "{% if ansible_memory_mb.real.total <ram_prereq_mb -%}FAILED
               {%- else -%}PASSED
               {%- endif %}"

- name: show check list
  debug:
    var: checklist

- name: store the result in a json
  copy:
    dest: /tmp/{{ ansible_hostname }}_prevalidaton_result.json
    content: "{{ checklist }}"

- name: host checklist post update for  provisioning validation
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_all.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "Pre Validation"
    task_id: "{{ ticket_ref }}"
    task_status: "FAILED"
    task_message: " Prevalidations for Provisioning on {{ ansible_hostname }}"
    standard_task_id: "{{ standard_task_id }}"
  when: checklist | json_query('[?status == `FAILED`]') | length > 1
  tags:
  - apex_api

- name: host checklist post update for  provisioning validation
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_all.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "Pre Validation"
    task_id: "{{ ticket_ref }}"
    task_status: "SUCCESSFUL"
    task_message: "Prevalidations for Provisioning on {{ ansible_hostname }}"
    standard_task_id: "{{ standard_task_id }}"
  when: checklist | json_query('[?status == `FAILED`]') | length == 0
  tags:
  - apex_api


- name: db checklist status file upload for prevalistion
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_file.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "Pre Validation"
    task_id: "{{ ticket_ref }}"
    task_status: "Upload Pre Validation checklist"
    task_message: "Prevalidations checklist {{ ansible_hostname }} "
    file_mimetype: "text/plain"
    record_type: "file_upload"
    logfile_path: "/tmp/{{ ansible_hostname }}_prevalidaton_result.json"
    standard_task_id: "{{ standard_task_id_val }}"
  tags:
  - apex_api

- name: Check for Precheck Failures
  fail:
    msg: "{% if checklist | json_query('[?status == `FAILED`]') | length == 1 -%}You have 1 failed check
          {%- else -%}You have {{ checklist | json_query('[?status == `FAILED`]') | length }} failed checks
          {%- endif %}"
  when: checklist | json_query('[?status == `FAILED`]') | length > 0
  tags:
    - precheck_fail
    - preval_fail
