---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml

# tasks file for postgresql-prevalidation
#TODO: add  ansible_distribution precheck
- name: generate checklist output
  set_fact:
    checklist:
    # - check_name: Linux distro version
    #   expected_value: "{{ distro_version }}"
    #   actual_value: "{{ ansible_distribution_major_version }}"
    #   status: "{% if ansible_distribution_major_version not in distro_version  -%}FAILED
    #             {%- else -%}PASSED
    #             {%- endif %}"
    - check_name: CPU count
      expected_value: " {{ cpu_count_prereq }}  or more"
      actual_value: "{{ ansible_processor_count }}"
      status: "{% if ansible_processor_count | int < cpu_count_prereq |int -%}FAILED
               {%- else -%}PASSED
               {%- endif %}"
    - check_name: core per cpu count
      expected_value: " {{ core_count_prereq }}  or more"
      actual_value: "{{ ansible_processor_cores }}"
      status: "{% if ansible_processor_cores | int < core_count_prereq |default('1') |int -%}FAILED
               {%- else -%}PASSED
               {%- endif %}"
    - check_name: memory count
      expected_value: "{{ ram_prereq_mb }} or higher"
      actual_value: "{{ ansible_memory_mb.real.total }}"
      status: "{% if ansible_memory_mb.real.total <ram_prereq_mb -%}FAILED
               {%- else -%}PASSED
               {%- endif %}"

- name: show check list
  debug:
    var: checklist

- name: store the result in a json
  copy:
    dest: /tmp/{{ ansible_hostname }}_prevalidaton_result.json
    content: "{{ checklist }}"

- name: Check for Precheck Failures
  fail:
    msg: "{% if checklist | json_query('[?status == `FAILED`]') | length == 1 -%}You have 1 failed check
          {%- else -%}You have {{ checklist | json_query('[?status == `FAILED`]') | length }} failed checks
          {%- endif %}"
  when: checklist | json_query('[?status == `FAILED`]') | length > 0
  tags:
    - precheck_fail
    - preval_fail
