---
# tasks file for postgresql-backup-db

- name: db checklist status post for dump  db
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_all.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "DB BACKUP"
    task_id: "{{ ticket_ref }}"
    task_status: "STARTED"
    task_message: "Dumping {{ db_name}} "
    standard_task_id: "{{ standard_task_id }}"
  tags:
  - apex_api
  
- block:
    - name: Dump an existing database to a file
      postgresql_db:
        name: "{{ db_name }}"
        state: dump
        target: "{{ local_path }}{{ db_name }}.sql"
      become: true
      become_user: postgres
  rescue:
    - name: db checklist status post for dump DB
      import_role:
        name: dbaas_api_services
        tasks_from: db_checklist_status_all.yml
      vars:
        task_key: "{{ ansible_hostname }}"
        task_area: "DB BACKUP"
        task_id: "{{ ticket_ref }}"
        task_status: "FAILED"
        task_message: "Creating Database {{ db_name }} "
        standard_task_id: "{{ standard_task_id }}"
      tags:
      - apex_api
    
    - name: db backup failed
      fail:
        msg: db  {{ db_name}}  backup failed

- include_tasks: s3.yml
  when: s3 is defined
  tags: 
   - s3

- name: db checklist status post for dump DB
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_all.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "DB INSTANCE CREATION"
    task_id: "{{ ticket_ref }}"
    task_status: "SUCCESSFUL"
    task_message: " backup for {{ db_name }} was created "
    standard_task_id: "{{ standard_task_id }}"
  tags:
  - apex_api
