---
# tasks file for postgresql-backup-db
- block:
    - name: Dump an existing database to a file
      postgresql_db:
        name: "{{ db_name }}"
        state: dump
        target: "{{ local_path }}{{ db_name }}.sql"
      become: true
      become_user: postgres
  rescue:    
    - name: db backup failed
      fail:
        msg: db  {{ db_name}}  backup failed

- include_tasks: s3.yml
  when: s3 is defined
  tags: 
   - s3