---
- name: include variables
  include_vars: secrets.yml
  no_log: True

- name: db checklist status post for dump DB
  import_role:
    name: dbaas_api_services
    tasks_from: db_checklist_status_all.yml
  vars:
    task_key: "{{ ansible_hostname }}"
    task_area: "DB BACKUP"
    task_id: "{{ ticket_ref }}"
    task_status: "IN PROGRESS"
    task_message: " Uploading backup to s3 bucket {{ bucket }}"
    standard_task_id: "{{ standard_task_id }}"
  tags:
  - apex_api

- block:
    - name: install boto3 prerequisites
      pip:
        state: present
        name:
        - boto3
        - boto
      become: true

    - name: uploading backup to S3
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "{{ bucket }}"
        object: "{{ s3_path }}{{ db_name }}.sql"
        src:  "{{ local_path }}{{ db_name }}.sql"
        mode: put
  rescue:
    - name: db checklist status post for dump DB
      import_role:
        name: dbaas_api_services
        tasks_from: db_checklist_status_all.yml
      vars:
        task_key: "{{ ansible_hostname }}"
        task_area: "DB BACKUP"
        task_id: "{{ ticket_ref }}"
        task_status: "FAILED"
        task_message: "Failed to upload to S3  {{ db_name }} backup"
        standard_task_id: "{{ standard_task_id }}"
      tags:
      - apex_api
    
    - name: db backup failed
      fail:
        msg: db  {{ db_name }}  backup failed