---
- name: include variables
  include_vars: secrets.yml
  no_log: True

- block:
    - name: install boto3 prerequisites
      pip:
        state: present
        name:
        - boto3
        - boto
      become: true

    - name: uploading backup to S3
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "{{ bucket }}"
        object: "{{ s3_path }}{{ db_name }}.sql"
        src:  "{{ local_path }}{{ db_name }}.sql"
        mode: put
  rescue:
    - name: db backup failed
      fail:
        msg: db  {{ db_name }}  backup failed