---
postgres_version: "{{ version }}"
postgres_repo_name: "pgdg{{ postgres_version | replace('.','') }}"
postgres_repo_url: "https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat/rhel-$releasever-$basearch"
postgres_repo_key: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgres_version | replace('.','') }}"
postgres_packages:
  - postgresql{{ postgres_version | replace('.','') }}-server
  - postgresql{{ postgres_version | replace('.','') }}-contrib
  - postgresql-contrib
  - postgresql
  - postgresql-libs
  - python-psycopg2
  - postgresql-devel
  - python-pip
  - libselinux-python
  - openssh
#postgres_home:  "{% for disk in instances.ebs_block_device %}{% if disk.device_type == 'data' %}{{ disk.mount_point }}{% endif %}{% endfor %}"
postgres_service_name: "postgresql-{{ postgres_version }}"
postgres_initdb_command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql{{ (postgres_version is version_compare('10', '>=')) | ternary('-','') }}{{ postgres_version | replace('.','') }}-setup initdb"
#postgres_data_directory: "{{ postgres_home }}/{{ postgres_version }}/data"
#postgres_config_file: "{{ postgres_data_directory }}/postgresql.conf"
#postgres_hba_file: "{{ postgres_data_directory }}/pg_hba.conf"
epel_url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'