---
postgres_version: 9.4
postgres_repo_name: "pgdg{{ postgres_version | replace('.','') }}"
postgres_repo_url: "https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat/rhel-$releasever-$basearch"
postgres_repo_key: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgres_version | replace('.','') }}"
postgres_packages:
  - postgresql{{ postgres_version | replace('.','') }}-server
  - postgresql{{ postgres_version | replace('.','') }}-contrib
  - postgresql-contrib
  - postgresql
  - postgresql-libs
  - python-psycopg2
  - postgresql-devel
  - python-pip
  - libselinux-python
  - openssh
postgres_home: "/var/lib/pgsql"
postgres_service_name: "postgresql-{{ postgres_version }}"
postgres_initdb_command: "service {{ postgres_service_name }} initdb"
postgres_data_directory: "/var/lib/pgsql/{{ postgres_version }}/data"
postgres_config_file: "{{ postgres_data_directory }}/postgresql.conf"
postgres_hba_file: "{{ postgres_data_directory }}/pg_hba.conf"
epel_url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm'