---
postgres_version: "{{ (upgrade_to_version| string).split('.')[0] is version_compare('10', '>=') | ternary(( upgrade_to_version| string).split('.')[0] ,(upgrade_to_version|  string).split('.')[0:2] | join('.')) }}"
postgres_version_old : "{{ current_version[0] is version_compare('10', '<') | ternary( current_version[0:2] | join('.'),current_version[0]) }}"
postgres_repo_name: "pgdg{{ postgres_version | replace('.','') }}"
postgres_repo_url: "https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat/rhel-$releasever-$basearch"
postgres_repo_key: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgres_version | replace('.','') }}"
postgres_packages:
  - postgresql{{ postgres_version | replace('.','') }}-server
  - postgresql{{ postgres_version | replace('.','') }}-contrib
  - postgresql{{ postgres_version | replace('.','') }}-libs
  - postgresql{{ postgres_version | replace('.','') }}
  - postgresql{{ postgres_version | replace('.','') }}-devel

postgres_packages_minor:
  - postgresql{{ postgres_version | replace('.','') }}-server-{{ upgrade_to_version }}
  - postgresql{{ postgres_version | replace('.','') }}-contrib-{{ upgrade_to_version }}
  - postgresql{{ postgres_version | replace('.','') }}-libs-{{ upgrade_to_version }}
  - postgresql{{ postgres_version | replace('.','') }}-{{ upgrade_to_version }}
  - postgresql{{ postgres_version | replace('.','') }}-devel-{{ upgrade_to_version }}

prereq_packages:
  - python-psycopg2  
  - python-pip
  - libselinux-python
  - openssh
postgres_home: "/var/lib/pgsql"
postgres_binary: "/usr/pgsql-{{ postgres_version }}/bin"
postgres_binary_old: "/usr/pgsql-{{ postgres_version_old }}/bin"
postgres_service_name: "postgresql-{{ postgres_version }}"
postgres_service_name_old: "postgresql-{{ postgres_version_old }}"
postgres_initdb_command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql{{ (postgres_version is version_compare('10', '>=')) | ternary('-','') }}{{ postgres_version | replace('.','') }}-setup initdb"
postgres_data_directory: "/var/lib/pgsql/{{ postgres_version }}/data"
postgres_data_directory_old: "/var/lib/pgsql/{{ postgres_version_old }}/data"
postgres_config_file: "{{ postgres_data_directory }}/postgresql.conf"
postgres_config_file_old: "{{ postgres_data_directory_old }}/postgresql.conf"
postgres_hba_file: "{{ postgres_data_directory }}/pg_hba.conf"
postgres_hba_file_old: "{{ postgres_data_directory_old }}/pg_hba.conf"
epel_url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'