---
postgres_version: "{{ version | default('9.6 ')}}"
postgres_repo_url: http://apt.postgresql.org/pub/repos/apt/
postgres_repo_key: ACCC4CF8
postgres_repo_keyfile: postgres_pubkey.asc
postgres_packages:
  - postgresql-{{ postgres_version }}
  - libpq-dev
  - python-pip
  - build-essential
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - libpq-dev
  - libssl-dev
  - zlib1g-dev
  - libldap2-dev
  - libsasl2-
  - python-selinux
postgres_home: "/var/lib/postgresql"
postgres_service_name: postgresql
postgres_initdb_command: /bin/true
postgres_config_file: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
postgres_hba_file: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
postgres_data_directory: "{{ postgres_home }}/{{ postgres_version }}/main"
