---
postgres_version: "{{ version | default('9.6') }}"
postgres_repo_name: "pgdg{{ postgres_version | replace('.','') }}"
postgres_base_repo_url: "https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat"
postgres_repo_url: "{{ postgres_base_repo_url }}/rhel-$releasever-$basearch"
postgres_repo_key: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgres_version | replace('.','') }}"
postgres_packages:
  - postgresql{{ postgres_version | replace('.','') }}-server #add after testing
  - postgresql{{ postgres_version | replace('.','') }}-contrib
  - postgresql{{ postgres_version | replace('.','') }}-libs
  - postgresql{{ postgres_version | replace('.','') }}
  - postgresql{{ postgres_version | replace('.','') }}-devel
  - python-psycopg2
  - python-pip
  - libselinux-python
  - openssh

#postgres_home:  "{% for disk in instances.ebs_block_device %}{% if disk.device_type == 'data' %}{{ disk.mount_point }}/{{ version }}{% endif %}{% endfor %}"
postgres_home: "{{ postgres_data_dir }}/{{ version }}"
postgres_service_name: "postgresql-{{ postgres_version }}"
postgres_initdb_command: "/usr/pgsql-{{ postgres_version }}/bin/initdb"
postgres_data_directory: "{{ postgres_home }}/data"
postgres_config_file: "{{ postgres_data_directory }}/postgresql.conf"
postgres_hba_file: "{{ postgres_data_directory }}/pg_hba.conf"
epel_url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
