---
postgres_packages:
  - postgresql94-server
postgres_service_name: postgresql
postgres_initdb_command: service postgresql start
postgres_config_file: /var/lib/pgsql/data/postgresql.conf
postgres_hba_file: /var/lib/pgsql/data/pg_hba.conf
postgres_home: "/var/lib/pgsql"