---
# tasks file for postgresql-create-db
- block:
    - name: Creating databases
      postgresql_db:
        name: "{{ item.name }}"
        encoding: "{{ db_encoding }}"
        lc_collate: "{{ db_collate }}"
        lc_ctype: "{{ db_ctype }}"
      become: true
      become_user: postgres
      register: create_result
      loop: "{{ postgresql_databases }}"
      
  when: inventory_hostname not in groups['SLAVE_HOST']
  rescue:
    - name: Instance Creation Failed
      fail:
        msg: Creation of databases failed